name: Test batch_processing.sh

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - '*'
  schedule:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
    # > Scheduled workflows run on the latest commit on the default or base branch
    # i.e. this can only run on master
    - cron:  '0 11 * * *'

env:
  # Turns on color output for pytest. See: https://github.com/pytest-dev/pytest/issues/7443#issuecomment-656642591
  PY_COLORS: "1"
  # Used in 'pytest.mark.skipif()' for test, which prevents the test from being run during the usual test suite
  TEST_BATCH_PROCESSING: "1"
  # Disable progress bars for less verbose output
  PIP_PROGRESS_BAR: "off"
  SCT_PROGRESS_BAR: "off"

jobs:
  batch_processing:
    name: Test batch_processing.sh
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0 ]
                              # macOS currently fails due to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3194
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get CPU model name
        id: get_cpu_name
        run: |
          model_name=$(lscpu | sed -nr '/Model name/ s/.*:\s*(.*) @ .*/\1/p')
          echo $model_name
          echo "::set-output name=cpu_name::$model_name"

      - name: Checkout SCT
        if: ${{ steps.get_cpu_name.outputs.cpu_name == 'Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz' }}
        uses: actions/checkout@v2

      # install_sct edits ~/.bashrc, but those environment changes don't get passed to subsequent steps in GH Actions.
      # So, we filter through the .bashrc and pass the values to $GITHUB_ENV and $GITHUB_PATH.
      # Relevant documentation: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
      # This workaround should be replaced by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3198#discussion_r568225392
      - name: Install SCT
        if: ${{ steps.get_cpu_name.outputs.cpu_name == 'Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz' }}
        run: |
          ./install_sct -y
          cat ~/.bashrc | grep "export SCT_DIR" | cut -d " " -f 2 >> $GITHUB_ENV
          cat ~/.bashrc | grep "export PATH" | grep -o "/.*" | cut -d ':' -f 1 >> $GITHUB_PATH

      - name: Run batch_processing.sh
        if: ${{ steps.get_cpu_name.outputs.cpu_name == 'Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz' }}
        run: |
          ./batch_processing_mini.sh

      - name: Upload 1mm resample product artifact
        if: ${{ steps.get_cpu_name.outputs.cpu_name == 'Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz' }}
        uses: actions/upload-artifact@v2
        with:
          name: resample_tmp
          path: |
            ftmp_data_1mm.nii.gz
            ftmp_seg_1mm.nii.gz
            ftmp_label_1mm.nii.gz
